/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetocalculadora;

import calculadorafuncionalidades.CalculadoraFuncoes;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;
import javax.swing.JOptionPane;
import java.awt.Toolkit;

/**
 *
 * @author selan
 */
public class Calculadora extends javax.swing.JFrame {
    
    
    private final CalculadoraFuncoes calculadora;
    private String ultimaOperacao;
    private final String soma = "SOMA";
    private final String subtracao = "SUBTRACAO";
    private final String divisao = "DIVISAO";
    private final String multiplicacao = "MULTIPLICACAO";
    private final String resto = "RESTO";
    /**
     * Creates new form Calculadora
     */
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("calculadora.png")));
    }
    
    public Calculadora() {
        initComponents();
        setIcon();
        calculadora = new CalculadoraFuncoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btResetar = new javax.swing.JButton();
        btCalcular = new javax.swing.JButton();
        btAdicao = new javax.swing.JButton();
        btSubtracao = new javax.swing.JButton();
        btMultiplicacao = new javax.swing.JButton();
        btDivisao = new javax.swing.JButton();
        btRestoDiv = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btCoracao = new javax.swing.JButton();
        Visor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 204), 1, true));
        jPanel1.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btResetar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btResetar.setForeground(new java.awt.Color(153, 0, 51));
        btResetar.setText("C");
        btResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetarActionPerformed(evt);
            }
        });

        btCalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCalcular.setForeground(new java.awt.Color(51, 0, 51));
        btCalcular.setText("=");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        btAdicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAdicao.setForeground(new java.awt.Color(51, 0, 51));
        btAdicao.setText("+");
        btAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicaoActionPerformed(evt);
            }
        });

        btSubtracao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSubtracao.setForeground(new java.awt.Color(51, 0, 51));
        btSubtracao.setText("-");
        btSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubtracaoActionPerformed(evt);
            }
        });

        btMultiplicacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btMultiplicacao.setForeground(new java.awt.Color(51, 0, 51));
        btMultiplicacao.setText("*");
        btMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultiplicacaoActionPerformed(evt);
            }
        });

        btDivisao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btDivisao.setForeground(new java.awt.Color(51, 0, 51));
        btDivisao.setText("/");
        btDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivisaoActionPerformed(evt);
            }
        });

        btRestoDiv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btRestoDiv.setForeground(new java.awt.Color(51, 0, 51));
        btRestoDiv.setText("%");
        btRestoDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRestoDivActionPerformed(evt);
            }
        });

        bt7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt7.setForeground(new java.awt.Color(51, 0, 51));
        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        bt8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt8.setForeground(new java.awt.Color(51, 0, 51));
        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt9.setForeground(new java.awt.Color(51, 0, 51));
        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        bt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt4.setForeground(new java.awt.Color(51, 0, 51));
        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt5.setForeground(new java.awt.Color(51, 0, 51));
        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt6.setForeground(new java.awt.Color(51, 0, 51));
        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt1.setForeground(new java.awt.Color(51, 0, 51));
        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt2.setForeground(new java.awt.Color(51, 0, 51));
        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt3.setForeground(new java.awt.Color(51, 0, 51));
        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt0.setForeground(new java.awt.Color(51, 0, 51));
        bt0.setText("0");
        bt0.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bt0FocusGained(evt);
            }
        });
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });

        btCoracao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCoracao.setForeground(new java.awt.Color(51, 0, 51));
        btCoracao.setText("♥");
        btCoracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCoracaoActionPerformed(evt);
            }
        });

        Visor.setEditable(false);
        Visor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Visor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Visor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51)));
        Visor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Visor.setFocusable(false);
        Visor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Visor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btResetar, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCoracao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btRestoDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSubtracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Visor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btResetar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicao)
                    .addComponent(bt7)
                    .addComponent(bt8)
                    .addComponent(bt9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt5)
                    .addComponent(bt4)
                    .addComponent(bt6)
                    .addComponent(btSubtracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1)
                    .addComponent(bt2)
                    .addComponent(bt3)
                    .addComponent(btMultiplicacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRestoDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCoracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        btResetar.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetarActionPerformed
        limpaVisor();
        calculadora.zerarTotal();
        System.out.println();
    }//GEN-LAST:event_btResetarActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        if (ultimaOperacao.equals(divisao) && Visor.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "Você tentou dividir por '0'", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            calculadora.zerarTotal(); 
            limpaVisor();
            System.out.println();
            
        } else {
            System.out.print(Visor.getText());
            calculadora.realizaCalculo(ultimaOperacao, converteEmInteiro(Visor.getText()));
            Visor.setText(converteEmString(calculadora.getTotal()));
            System.out.println(" = " + Visor.getText());
            calculadora.zerarTotal(); // Para esquecer os calculos anteriores!!!
        }
    }//GEN-LAST:event_btCalcularActionPerformed

    private void btMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultiplicacaoActionPerformed
        //valorDigitado("*");
        if (Visor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Esta é uma operação binária! ^-^", "Atenção", JOptionPane.ERROR_MESSAGE);
            limpaVisor();
            System.out.println();
        } else {
            if (converteEmInteiro(Visor.getText()) <= 999 && converteEmInteiro(Visor.getText()) >= -999){
                calculadora.realizaCalculo(multiplicacao, converteEmInteiro(Visor.getText()));
                System.out.print( Visor.getText() +  " * ");
                ultimaOperacao = multiplicacao;
                limpaVisor();
            } else {
                JOptionPane.showMessageDialog(null, "Só aceitamos valores de até três digitos! ^-^", "Atenção", JOptionPane.ERROR_MESSAGE);
                limpaVisor();
                System.out.println();
            }
        }
    }//GEN-LAST:event_btMultiplicacaoActionPerformed
    
    private void VisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisorActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        valorDigitado("0");
    }//GEN-LAST:event_bt0ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        valorDigitado("1");
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        valorDigitado("2");
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        valorDigitado("3");
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        valorDigitado("4");
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        valorDigitado("5");
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        valorDigitado("6");
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        valorDigitado("7");
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        valorDigitado("8");
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        valorDigitado("9");
    }//GEN-LAST:event_bt9ActionPerformed

    private void btDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivisaoActionPerformed
        //valorDigitado("/");
        
        if (Visor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Esta é uma operação binária! ^-^", "Atenção", JOptionPane.ERROR_MESSAGE);
            limpaVisor();
            System.out.println();
        } else {
            if (converteEmInteiro(Visor.getText()) <= 999 && converteEmInteiro(Visor.getText()) >= -999){
                if (Visor.getText().equals("0")){
                    calculadora.realizaCalculo(divisao, 1);
                    System.out.print( Visor.getText() +  " / ");
                    ultimaOperacao = divisao;
                    limpaVisor();
                } else {
                    calculadora.realizaCalculo(divisao, converteEmInteiro(Visor.getText()));
                    System.out.print( Visor.getText() +  " / ");
                    ultimaOperacao = divisao;
                    limpaVisor();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Só aceitamos valores de até três digitos! ^-^", "Atenção", JOptionPane.ERROR_MESSAGE);
                limpaVisor();
                System.out.println();
            }
        }
    }//GEN-LAST:event_btDivisaoActionPerformed

    private void btSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubtracaoActionPerformed
        
        if (converteEmInteiro(Visor.getText()) <= 999 && converteEmInteiro(Visor.getText()) >= -999){
            if (Visor.getText().equals("")){
                Visor.setText("-");
            } else {
                calculadora.realizaCalculo(subtracao, converteEmInteiro(Visor.getText()));
                System.out.print( Visor.getText() +  " - ");
                ultimaOperacao = subtracao;
                limpaVisor();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Só aceitamos valores de até três digitos! ^-^", "Atenção", JOptionPane.ERROR_MESSAGE);
            limpaVisor();
            System.out.println();
        }
    }//GEN-LAST:event_btSubtracaoActionPerformed

    private void btAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicaoActionPerformed
        //valorDigitado("+");
        if (converteEmInteiro(Visor.getText()) <= 999 && converteEmInteiro(Visor.getText()) >= -999){
            calculadora.realizaCalculo(soma, converteEmInteiro(Visor.getText()));
            System.out.print( Visor.getText() +  " + ");
            ultimaOperacao = soma;
            limpaVisor();
        } else {
            JOptionPane.showMessageDialog(null, "Só aceitamos valores de até três digitos! ^-^", "Atenção", JOptionPane.ERROR_MESSAGE);
            limpaVisor();
            System.out.println();
        }
    }//GEN-LAST:event_btAdicaoActionPerformed

    private void btCoracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCoracaoActionPerformed
        System.exit(0);
        //Visor.setText(converteEmString((-1)*converteEmInteiro(Visor.getText())));
    }//GEN-LAST:event_btCoracaoActionPerformed

    private void btRestoDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRestoDivActionPerformed
        if (Visor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Esta é uma operação binária! ^-^", "Atenção", JOptionPane.ERROR_MESSAGE);
            limpaVisor();
            System.out.println();
        } else {
            if (converteEmInteiro(Visor.getText()) <= 999 && converteEmInteiro(Visor.getText()) >= -999){
                calculadora.realizaCalculo( resto, converteEmInteiro(Visor.getText()) );
                System.out.print( Visor.getText() +  " % ");
                ultimaOperacao = resto;
                limpaVisor();
            } else {
                JOptionPane.showMessageDialog(null, "Só aceitamos valores de até três digitos! ^-^", "Atenção", JOptionPane.ERROR_MESSAGE);
                limpaVisor();
                System.out.println();
            }
        }
    }//GEN-LAST:event_btRestoDivActionPerformed

    private void bt0FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bt0FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_bt0FocusGained

    // Meus metodos
    private void valorDigitado( String caractere ){
        if ( Visor.getText().equals("") ){
            Visor.setText(caractere);// Seto para o valor inserido
        } else {
            Visor.setText(Visor.getText().concat(caractere));// Concateno o que tenho com o que veio
        }
    }
    
    private Integer converteEmInteiro( String numero ){
        NumberFormat n = NumberFormat.getInstance();
        Integer d = 0;
        
        try {
            d = n.parse(numero).intValue();
        } catch ( ParseException ex ) {
            
        }
        return d;
    }
    
    private String converteEmString ( Integer numero ){
        if ( numero != null ){
            DecimalFormat formato = new DecimalFormat("##########", new DecimalFormatSymbols(new Locale("pt","BR")));
            formato.setParseBigDecimal(true);
            return formato.format(numero);
        }
        return "";
    }
    
    private void limpaVisor(  ){
        Visor.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Visor;
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btAdicao;
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btCoracao;
    private javax.swing.JButton btDivisao;
    private javax.swing.JButton btMultiplicacao;
    private javax.swing.JButton btResetar;
    private javax.swing.JButton btRestoDiv;
    private javax.swing.JButton btSubtracao;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
